version: "3"
services:
  database:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: temp_measurement
    restart: always

  backend:
    container_name: temp_measure
    build:
      context: ./server/Temperature_Measurement/
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/temp_measurement
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    volumes:
          - ./database-scripts:/docker-entrypoint-initdb.d
    restart: always

  web:
    restart: always
    container_name: react
    build:
      context: ./frontend/temp_measurement/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
